# Generated by Django 2.1.5 on 2019-02-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('shorturl', models.CharField(max_length=10, primary_key=True)),
                ('originalurl', models.CharField(max_length=300))
            ],
        ),
    ]
