# Generated by Django 2.1.5 on 2019-02-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalurl', models.CharField(max_length=300)),
                ('tinyurl', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
